#############################################################################
# Makefile for building: BBB2
# Generated by qmake (2.01a) (Qt 4.6.3) on: Sat Jun 4 11:12:54 2016
# Project:  BBB2.pro
# Template: app
# Command: /usr/local/angstrom/arm/bin/qmake2 -unix -o Makefile BBB2.pro
#############################################################################

####### Compiler, tools and options

CC            = $(OE_QMAKE_CC)
CXX           = $(OE_QMAKE_CXX)
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe $(OE_QMAKE_CFLAGS) -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe $(OE_QMAKE_CFLAGS) $(OE_QMAKE_CXXFLAGS) -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/local/angstrom/arm/arm-angstrom-linux-gnueabi/usr/share/qtopia/mkspecs/linux-g++ -I. -I$(OE_QMAKE_INCDIR_QT)/QtCore -I$(OE_QMAKE_INCDIR_QT)/QtGui -I$(OE_QMAKE_INCDIR_QT) -I. -I.
LINK          = $(OE_QMAKE_LINK)
LFLAGS        = $(OE_QMAKE_LDFLAGS)
LIBS          = $(SUBLIBS)  -L$(OE_QMAKE_LIBDIR_QT) -lQtGuiE -lQtNetworkE -lQtCoreE -lglib-2.0 -lpthread 
AR            = $(OE_QMAKE_AR) cqs
RANLIB        = 
QMAKE         = /usr/local/angstrom/arm/bin/qmake2
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = $(OE_QMAKE_STRIP)
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		inputs.cpp \
		symptoms.cpp \
		send.cpp \
		basic.cpp moc_inputs.cpp \
		moc_symptoms.cpp \
		moc_send.cpp \
		moc_basic.cpp
OBJECTS       = main.o \
		inputs.o \
		symptoms.o \
		send.o \
		basic.o \
		moc_inputs.o \
		moc_symptoms.o \
		moc_send.o \
		moc_basic.o
DIST          = /usr/local/angstrom/arm/arm-angstrom-linux-gnueabi/usr/share/qtopia/mkspecs/common/g++.conf \
		/usr/local/angstrom/arm/arm-angstrom-linux-gnueabi/usr/share/qtopia/mkspecs/common/unix.conf \
		/usr/local/angstrom/arm/arm-angstrom-linux-gnueabi/usr/share/qtopia/mkspecs/common/linux.conf \
		/usr/local/angstrom/arm/arm-angstrom-linux-gnueabi/usr/share/qtopia/mkspecs/qconfig.pri \
		/usr/local/angstrom/arm/arm-angstrom-linux-gnueabi/usr/share/qtopia/mkspecs/features/qt_functions.prf \
		/usr/local/angstrom/arm/arm-angstrom-linux-gnueabi/usr/share/qtopia/mkspecs/features/qt_config.prf \
		/usr/local/angstrom/arm/arm-angstrom-linux-gnueabi/usr/share/qtopia/mkspecs/features/exclusive_builds.prf \
		/usr/local/angstrom/arm/arm-angstrom-linux-gnueabi/usr/share/qtopia/mkspecs/features/default_pre.prf \
		/usr/local/angstrom/arm/arm-angstrom-linux-gnueabi/usr/share/qtopia/mkspecs/features/release.prf \
		/usr/local/angstrom/arm/arm-angstrom-linux-gnueabi/usr/share/qtopia/mkspecs/features/default_post.prf \
		/usr/local/angstrom/arm/arm-angstrom-linux-gnueabi/usr/share/qtopia/mkspecs/features/warn_on.prf \
		/usr/local/angstrom/arm/arm-angstrom-linux-gnueabi/usr/share/qtopia/mkspecs/features/qt.prf \
		/usr/local/angstrom/arm/arm-angstrom-linux-gnueabi/usr/share/qtopia/mkspecs/features/unix/thread.prf \
		/usr/local/angstrom/arm/arm-angstrom-linux-gnueabi/usr/share/qtopia/mkspecs/features/moc.prf \
		/usr/local/angstrom/arm/arm-angstrom-linux-gnueabi/usr/share/qtopia/mkspecs/features/resources.prf \
		/usr/local/angstrom/arm/arm-angstrom-linux-gnueabi/usr/share/qtopia/mkspecs/features/uic.prf \
		/usr/local/angstrom/arm/arm-angstrom-linux-gnueabi/usr/share/qtopia/mkspecs/features/yacc.prf \
		/usr/local/angstrom/arm/arm-angstrom-linux-gnueabi/usr/share/qtopia/mkspecs/features/lex.prf \
		/usr/local/angstrom/arm/arm-angstrom-linux-gnueabi/usr/share/qtopia/mkspecs/features/include_source_dir.prf \
		BBB2.pro
QMAKE_TARGET  = BBB2
DESTDIR       = 
TARGET        = BBB2

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_inputs.h ui_symptoms.h ui_send.h ui_basic.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: BBB2.pro  /usr/local/angstrom/arm/arm-angstrom-linux-gnueabi/usr/share/qtopia/mkspecs/linux-g++/qmake.conf /usr/local/angstrom/arm/arm-angstrom-linux-gnueabi/usr/share/qtopia/mkspecs/common/g++.conf \
		/usr/local/angstrom/arm/arm-angstrom-linux-gnueabi/usr/share/qtopia/mkspecs/common/unix.conf \
		/usr/local/angstrom/arm/arm-angstrom-linux-gnueabi/usr/share/qtopia/mkspecs/common/linux.conf \
		/usr/local/angstrom/arm/arm-angstrom-linux-gnueabi/usr/share/qtopia/mkspecs/qconfig.pri \
		/usr/local/angstrom/arm/arm-angstrom-linux-gnueabi/usr/share/qtopia/mkspecs/features/qt_functions.prf \
		/usr/local/angstrom/arm/arm-angstrom-linux-gnueabi/usr/share/qtopia/mkspecs/features/qt_config.prf \
		/usr/local/angstrom/arm/arm-angstrom-linux-gnueabi/usr/share/qtopia/mkspecs/features/exclusive_builds.prf \
		/usr/local/angstrom/arm/arm-angstrom-linux-gnueabi/usr/share/qtopia/mkspecs/features/default_pre.prf \
		/usr/local/angstrom/arm/arm-angstrom-linux-gnueabi/usr/share/qtopia/mkspecs/features/release.prf \
		/usr/local/angstrom/arm/arm-angstrom-linux-gnueabi/usr/share/qtopia/mkspecs/features/default_post.prf \
		/usr/local/angstrom/arm/arm-angstrom-linux-gnueabi/usr/share/qtopia/mkspecs/features/warn_on.prf \
		/usr/local/angstrom/arm/arm-angstrom-linux-gnueabi/usr/share/qtopia/mkspecs/features/qt.prf \
		/usr/local/angstrom/arm/arm-angstrom-linux-gnueabi/usr/share/qtopia/mkspecs/features/unix/thread.prf \
		/usr/local/angstrom/arm/arm-angstrom-linux-gnueabi/usr/share/qtopia/mkspecs/features/moc.prf \
		/usr/local/angstrom/arm/arm-angstrom-linux-gnueabi/usr/share/qtopia/mkspecs/features/resources.prf \
		/usr/local/angstrom/arm/arm-angstrom-linux-gnueabi/usr/share/qtopia/mkspecs/features/uic.prf \
		/usr/local/angstrom/arm/arm-angstrom-linux-gnueabi/usr/share/qtopia/mkspecs/features/yacc.prf \
		/usr/local/angstrom/arm/arm-angstrom-linux-gnueabi/usr/share/qtopia/mkspecs/features/lex.prf \
		/usr/local/angstrom/arm/arm-angstrom-linux-gnueabi/usr/share/qtopia/mkspecs/features/include_source_dir.prf \
		/usr/local/angstrom/arm/arm-angstrom-linux-gnueabi/usr/lib/libQtGuiE.prl \
		/usr/local/angstrom/arm/arm-angstrom-linux-gnueabi/usr/lib/libQtNetworkE.prl \
		/usr/local/angstrom/arm/arm-angstrom-linux-gnueabi/usr/lib/libQtCoreE.prl
	$(QMAKE) -unix -o Makefile BBB2.pro
/usr/local/angstrom/arm/arm-angstrom-linux-gnueabi/usr/share/qtopia/mkspecs/common/g++.conf:
/usr/local/angstrom/arm/arm-angstrom-linux-gnueabi/usr/share/qtopia/mkspecs/common/unix.conf:
/usr/local/angstrom/arm/arm-angstrom-linux-gnueabi/usr/share/qtopia/mkspecs/common/linux.conf:
/usr/local/angstrom/arm/arm-angstrom-linux-gnueabi/usr/share/qtopia/mkspecs/qconfig.pri:
/usr/local/angstrom/arm/arm-angstrom-linux-gnueabi/usr/share/qtopia/mkspecs/features/qt_functions.prf:
/usr/local/angstrom/arm/arm-angstrom-linux-gnueabi/usr/share/qtopia/mkspecs/features/qt_config.prf:
/usr/local/angstrom/arm/arm-angstrom-linux-gnueabi/usr/share/qtopia/mkspecs/features/exclusive_builds.prf:
/usr/local/angstrom/arm/arm-angstrom-linux-gnueabi/usr/share/qtopia/mkspecs/features/default_pre.prf:
/usr/local/angstrom/arm/arm-angstrom-linux-gnueabi/usr/share/qtopia/mkspecs/features/release.prf:
/usr/local/angstrom/arm/arm-angstrom-linux-gnueabi/usr/share/qtopia/mkspecs/features/default_post.prf:
/usr/local/angstrom/arm/arm-angstrom-linux-gnueabi/usr/share/qtopia/mkspecs/features/warn_on.prf:
/usr/local/angstrom/arm/arm-angstrom-linux-gnueabi/usr/share/qtopia/mkspecs/features/qt.prf:
/usr/local/angstrom/arm/arm-angstrom-linux-gnueabi/usr/share/qtopia/mkspecs/features/unix/thread.prf:
/usr/local/angstrom/arm/arm-angstrom-linux-gnueabi/usr/share/qtopia/mkspecs/features/moc.prf:
/usr/local/angstrom/arm/arm-angstrom-linux-gnueabi/usr/share/qtopia/mkspecs/features/resources.prf:
/usr/local/angstrom/arm/arm-angstrom-linux-gnueabi/usr/share/qtopia/mkspecs/features/uic.prf:
/usr/local/angstrom/arm/arm-angstrom-linux-gnueabi/usr/share/qtopia/mkspecs/features/yacc.prf:
/usr/local/angstrom/arm/arm-angstrom-linux-gnueabi/usr/share/qtopia/mkspecs/features/lex.prf:
/usr/local/angstrom/arm/arm-angstrom-linux-gnueabi/usr/share/qtopia/mkspecs/features/include_source_dir.prf:
/usr/local/angstrom/arm/arm-angstrom-linux-gnueabi/usr/lib/libQtGuiE.prl:
/usr/local/angstrom/arm/arm-angstrom-linux-gnueabi/usr/lib/libQtNetworkE.prl:
/usr/local/angstrom/arm/arm-angstrom-linux-gnueabi/usr/lib/libQtCoreE.prl:
qmake:  FORCE
	@$(QMAKE) -unix -o Makefile BBB2.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/BBB21.0.0 || $(MKDIR) .tmp/BBB21.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/BBB21.0.0/ && $(COPY_FILE) --parents inputs.h symptoms.h send.h basic.h .tmp/BBB21.0.0/ && $(COPY_FILE) --parents main.cpp inputs.cpp symptoms.cpp send.cpp basic.cpp .tmp/BBB21.0.0/ && $(COPY_FILE) --parents inputs.ui symptoms.ui send.ui basic.ui .tmp/BBB21.0.0/ && (cd `dirname .tmp/BBB21.0.0` && $(TAR) BBB21.0.0.tar BBB21.0.0 && $(COMPRESS) BBB21.0.0.tar) && $(MOVE) `dirname .tmp/BBB21.0.0`/BBB21.0.0.tar.gz . && $(DEL_FILE) -r .tmp/BBB21.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_inputs.cpp moc_symptoms.cpp moc_send.cpp moc_basic.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_inputs.cpp moc_symptoms.cpp moc_send.cpp moc_basic.cpp
moc_inputs.cpp: basic.h \
		symptoms.h \
		send.h \
		inputs.h
	$(OE_QMAKE_MOC) $(DEFINES) $(INCPATH) inputs.h -o moc_inputs.cpp

moc_symptoms.cpp: send.h \
		symptoms.h
	$(OE_QMAKE_MOC) $(DEFINES) $(INCPATH) symptoms.h -o moc_symptoms.cpp

moc_send.cpp: send.h
	$(OE_QMAKE_MOC) $(DEFINES) $(INCPATH) send.h -o moc_send.cpp

moc_basic.cpp: symptoms.h \
		send.h \
		basic.h
	$(OE_QMAKE_MOC) $(DEFINES) $(INCPATH) basic.h -o moc_basic.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_inputs.h ui_symptoms.h ui_send.h ui_basic.h
compiler_uic_clean:
	-$(DEL_FILE) ui_inputs.h ui_symptoms.h ui_send.h ui_basic.h
ui_inputs.h: inputs.ui
	$(OE_QMAKE_UIC) inputs.ui -o ui_inputs.h

ui_symptoms.h: symptoms.ui
	$(OE_QMAKE_UIC) symptoms.ui -o ui_symptoms.h

ui_send.h: send.ui
	$(OE_QMAKE_UIC) send.ui -o ui_send.h

ui_basic.h: basic.ui
	$(OE_QMAKE_UIC) basic.ui -o ui_basic.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp inputs.h \
		basic.h \
		symptoms.h \
		send.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

inputs.o: inputs.cpp inputs.h \
		basic.h \
		symptoms.h \
		send.h \
		ui_inputs.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o inputs.o inputs.cpp

symptoms.o: symptoms.cpp symptoms.h \
		send.h \
		ui_symptoms.h \
		inputs.h \
		basic.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o symptoms.o symptoms.cpp

send.o: send.cpp send.h \
		ui_send.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o send.o send.cpp

basic.o: basic.cpp basic.h \
		symptoms.h \
		send.h \
		inputs.h \
		ui_basic.h \
		ui_inputs.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o basic.o basic.cpp

moc_inputs.o: moc_inputs.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_inputs.o moc_inputs.cpp

moc_symptoms.o: moc_symptoms.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_symptoms.o moc_symptoms.cpp

moc_send.o: moc_send.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_send.o moc_send.cpp

moc_basic.o: moc_basic.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_basic.o moc_basic.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

